
<?php include("../Connections/Conn.php");?>

<?php
session_start();

if(isset($_GET['hosp_no'])){
	$hos_no=$_GET['hosp_no'];
}
		
$stmt = $db->prepare("SELECT fname, surname, oname FROM enrollee WHERE hospital_no = :hospital_no");
$stmt->bindParam(':hospital_no', $hos_no, PDO::PARAM_STR);
$stmt->execute();
$row_rs = $stmt->fetch(PDO::FETCH_ASSOC);

$names = $row_rs['surname'] . ' ' . $row_rs['fname'] . ' ' . $row_rs['oname'];
$setdate = date("Y-m-d");

?>			

<input type="button" onClick="window.print()"  value="PRINT"/>
&nbsp; | &nbsp;
<a href="<?php echo "index.php?presc&hos_no=$hos_no"?>">Close</a>

<table width="278" height="353" border="0" cellpadding="2" cellspacing="2" id="searchBorder" bgcolor="#FFFFFF">
    <tr>
    <td height="55" colspan="2"><div align="center"><b>
      <h3>INVOICE</h3>
    </b></div>

      <div align="center"><img src="../img/logo.png" width="98" height="55" /></div>
      <div align="center">(Hospital Copy)</div></td>
  </tr>
  <tr>
    <td width="106" height="31"><b>Hospital No:</b></td>
    <td width="149"><?php echo $hos_no; ?></td>
  </tr>
  <tr>
    <td height="27"><b>Names:</b></td>
    <td height="27"><?php echo $names; ?></td>
  </tr>
  <tr>
    <td height="136" colspan="2"><table width="270" border="0">
      <tr>
        <td width="33" height="23"><b>S/N</b></td>
        <td width="98"><b>Description</b></td>
        <td width="23"><b>Qty</b></td>
        <td width="98"><b>Amount</b></td>
      </tr>
      <tr>
     <?php
	 	
       $cnt = 1;
       $TotalTrans = 0;
       
       $stmtt = $db->prepare("SELECT * FROM saleprint WHERE hos_no = :hos_no ORDER BY sn");
       $stmtt->bindParam(':hos_no', $hos_no);
       $stmtt->execute();
       
       while($roww = $stmtt->fetch(PDO::FETCH_ASSOC)) {
           $sn = $roww['sale_no'];
           $item = $roww['item'];
           $pay = $roww['pay'];
           $claim = $roww['claim'];
           $qty = $roww['qty'];
           include_once("../inc/utilities.php");
           $invoice_no = INV();
       
           $updateSQL = "UPDATE patient_ap_services SET invoice_status = :invoice_status, invoice_no = :invoice_no, invoice_date = :invoice_date, invoice_by = :invoice_by WHERE hospital_no = :hospital_no AND sn = :sn AND serv_group = :serv_group";
           $stmt = $db->prepare($updateSQL);
           $stmt->bindValue(':invoice_status', '1');
           $stmt->bindParam(':invoice_no', $invoice_no);
           $stmt->bindParam(':invoice_date', $setdate);
           $stmt->bindParam(':invoice_by', $_SESSION['fullname']);
           $stmt->bindParam(':hospital_no', $hos_no);
           $stmt->bindParam(':sn', $sn);
           $stmt->bindValue(':serv_group', 'Pharmacy');
           $stmt->execute();
           
           $amt = ($pay > 0) ? $pay : $claim;
           ?>
       
           <tr>
               <td height="24"><?php echo $cnt; ?></td>
               <td><?php echo $item; ?></td>
               <td><?php echo $qty; ?></td>
               <td>N <?php echo number_format($amt, 2); 
               $TotalTrans += $amt;
               ?>
               </td>
           </tr>
       
           <?php
           $cnt++;
       }
       ?>
        <tr>
        <td height="13">&nbsp;</td>
        <td><b>Total:</b></td>
        <td>&nbsp;</td>
        <td>
		<hr  style="border:1px dotted;"/>
		<?php 
		echo "<strong>" . "N".number_format($TotalTrans,2,'.',',')."</strong>";
		  ?>
		<hr  style="border:1px dotted;"/></td>
      </tr>
    </table>
    <hr  style="border:1px dotted;"/></td>
  </tr>
  <tr>
    <td height="27"><b>Date &amp; Time:</b></td>
    <td height="27"><?php echo $setdate; ?></td>
  </tr>
  <tr>
    <td height="27"><b> Generated By:</b></td>
    <td height="27"><?php echo $_SESSION['fullname']; ?></td>
  </tr>
</table>
<table width="278" height="317" border="0" cellpadding="2" cellspacing="2" id="searchBorder" bgcolor="#FFFFFF">
  <tr>
    <td height="55" colspan="2"><div align="center"><b>
      <h3>INVOICE</h3>
    </b></div>
      <div align="center"><img src="../img/logo.png" width="98" height="55" /></div>
      <div align="center">(Patient's Copy)</div></td>
  </tr>
  <tr>
    <td width="106" height="31"><b>Hospital No:</b></td>
    <td width="149"><?php echo $hos_no; ?></td>
  </tr>
  <tr>
    <td height="27"><b>Names:</b></td>
    <td height="27"><?php echo $names; ?></td>
  </tr>
  <tr>
    <td height="136" colspan="2"><table width="270" border="0">
      <tr>
        <td height="23"><b>S/N</b></td>
        <td><b>Description</b></td>
        <td><b>Qty</b></td>
        <td><b>Amount</b></td>
      </tr>
      <tr>
     <?php
	 			$cnt=1;
				$TotalTrans=0;
	 $stmtt=$db->query("SELECT * FROM saleprint WHERE hos_no='$hos_no' order by sn");
		while($roww=$stmtt->fetch(PDO::FETCH_ASSOC)) {
				$sn = $roww['sale_no'];
				$item = $roww['item'];
						$pay = $roww['pay'];
					$claim = $roww['claim'];
					$qty = $roww['qty'];
 							
							if($pay>0){	
								$amt=$pay;
									}else{ 
										$amt=$claim;
										}
					?>

        <td height="24"><?php echo $cnt; ?></td>
        <td><?php echo $item; ?></td>
        <td><?php echo $qty; ?></td>
        <td>N <?php echo number_format($amt, 2); 
				$TotalTrans=$TotalTrans+$amt;
				?>
         </td>
      </tr>
      <?php
	  $cnt++;
		}
		?>      
      <tr>
        <td height="13">&nbsp;</td>
        <td><b>Total:</b></td>

        <td>&nbsp;</td>
        <td><hr  style="border:1px dotted;"/>
		<?php 
		echo "<strong>" . "N".number_format($TotalTrans,2,'.',',')."</strong>";
		  ?>
          <hr  style="border:1px dotted;"/></td>
      </tr>
    </table>
      <hr  style="border:1px dotted;"/></td>
  </tr>
  <tr>
    <td height="27"><b>Date &amp; Time:</b></td>
    <td height="27"><?php echo $setdate; ?></td>
  </tr>
  <tr>
    <td height="27"><b> Generated By:</b></td>
    <td height="27"><?php echo $_SESSION['fullname']; ?></td>
  </tr>
</table>

