                        <a href="javascript:Clickheretoprint()" target="_blank" class="btn btn-primary btn-xs"><i class="fa fa-print"></i> Print Report </a>
<div id="content">

<table width="278" height="353" border="0" cellpadding="2" cellspacing="2" id="searchBorder" bgcolor="#FFFFFF">
    <tr>
    <td height="55" colspan="2"><div align="center"><b>
      <h3><?php echo $header; ?></h3>
    </b></div>
      <div align="center"><img src="../img/logo.png" width="98" height="55" /></div>
      <div align="center">(Hospital Copy)</div></td>
  </tr>
  <tr>
    <td width="106" height="31"><b>Hospital No:</b></td>
    <td width="149"><?php echo $hos_no; ?></td>
  </tr>
  <tr>
    <td height="27"><b>Names:</b></td>
    <td height="27"><?php echo $names; ?></td>
  </tr>
  <tr>
    <td height="136" colspan="2"><table width="270" border="0">
      <tr>
        <td height="23"><b>S/N</b></td>
        <td><b>Description</b></td>
        <td><b>Qty</b></td>
        <td><b>Amount</b></td>
      </tr>
      <tr>
     <?php
	$cnt = 0;
	$TotalTrans=0;
	 $pro_inv=$_REQUEST['inv'];
	// echo $pro_inv;
	//print_r ($pro_inv);
			$amount=0;
		for($i=0;$i<count($pro_inv);$i++){
			//$inv_id = $pro_inv[$i];
			
						$inv_id = $pro_inv[$i];
				$break=explode("__",$inv_id);
		
				$sn=$break[0];
				$item_services=$break[1];
				$amount=$break[2];
				$qty=$break[3];
				$paystatus=$break[4];
				$transc_date=$break[5];
				$cnt++;
				
				?>
                
		<td height="24"><?php echo $cnt; ?></td>
        <td><?php echo $item_services; ?></td>
        <td><?php echo $qty; ?></td>
        <td><?php echo $amount; ?></td>
        <td><?php 
			$TotalTrans=$TotalTrans+$amount; 

		?>
        
        </td>
      </tr>
      <?php
		}
		?>
      <tr>
        <td height="13">&nbsp;</td>
        <td><b>Total:</b></td>
        <td>&nbsp;</td>
        <td>
		<hr  style="border:1px dotted;"/>
		<?php 
		echo "<strong>".number_format($TotalTrans)."</strong>";
		  ?>
		<hr  style="border:1px dotted;"/></td>
      </tr>
    </table>
    <hr  style="border:1px dotted;"/></td>
  </tr>
  <tr>
    <td height="27"><b>Date &amp; Time:</b></td>
    <td height="27"><?php echo $setdate; ?></td>
  </tr>
  <tr>
    <td height="27"><b> Generated By:</b></td>
    <td height="27"><?php echo $_SESSION['fullname']; ?></td>
  </tr>
</table>
<table width="278" height="317" border="0" cellpadding="2" cellspacing="2" id="searchBorder" bgcolor="#FFFFFF">
  <tr>
    <td height="55" colspan="2"><div align="center"><b>
      <h3><?php echo $header; ?></h3>
    </b></div>
      <div align="center"><img src="../img/logo.png" width="98" height="55" /></div>
      <div align="center">(Patient's Copy)</div></td>
  </tr>
  <tr>
    <td width="106" height="31"><b>Hospital No:</b></td>
    <td width="149"><?php echo $hos_no; ?></td>
  </tr>
  <tr>
    <td height="27"><b>Names:</b></td>
    <td height="27"><?php echo $names; ?></td>
  </tr>
  <tr>
    <td height="136" colspan="2"><table width="270" border="0">
      <tr>
        <td height="23"><b>S/N</b></td>
        <td><b>Description</b></td>
        <td><b>Qty</b></td>
        <td><b>Amount</b></td>
      </tr>
      <tr>
     <?php
	$cnt = 0;
	$TotalTrans=0;
	 $pro_inv=$_REQUEST['inv'];
	// echo $pro_inv;
	//print_r ($pro_inv);
			$amount=0;
		for($i=0;$i<count($pro_inv);$i++){
			//$inv_id = $pro_inv[$i];
						$inv_id = $pro_inv[$i];
				$break=explode("__",$inv_id);
		
				$sn=$break[0];
				$item_services=$break[1];
				$amount=$break[2];
				$qty=$break[3];
				$paystatus=$break[4];
				$transc_date=$break[5];

				$cnt++;?>
		<td height="24"><?php echo $cnt; ?></td>
        <td><?php echo $item_services; ?></td>
        <td><?php echo $qty; ?></td>
        <td><?php echo $amount; ?></td>
        <td><?php 
			$TotalTrans=$TotalTrans+$amount; 			
	}
		?>
        
        </td>
      </tr>
        </td>

      <tr>
        <td height="13">&nbsp;</td>
        <td><b>Total:</b></td>
        <td>&nbsp;</td>
        <td><hr  style="border:1px dotted;"/>
		<?php 
		//  $sqlSum = "SELECT *, SUM(pay) AS TotalTrans FROM patient_ap_services WHERE app_no='$app_no' AND invoice_status='1'";
		//$resSum = mysql_query($sqlSum);
		//$fetchSum = mysql_fetch_assoc($resSum);
		echo "<strong>".number_format($TotalTrans)."</strong>";
		  ?>
          <hr  style="border:1px dotted;"/></td>
      </tr>
    </table>
      <hr  style="border:1px dotted;"/></td>
  </tr>
  <tr>
    <td height="27"><b>Date &amp; Time:</b></td>
    <td height="27"><?php echo $setdate; ?></td>
  </tr>
  <tr>
    <td height="27"><b> Generated By:</b></td>
    <td height="27"><?php echo $_SESSION['fullname']; ?></td>
  </tr>
</table>

</div>